# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages: 
- stage: Buld
  jobs:
  - job: FirstJob
    steps:
    - bash: echo buld frst job
  - job: secondob
    steps:
    - bash: echo build second job

- stage: DevBuld
  jobs:
  - job: Firstob
    steps:
    - bash: echo buld frst job
  - job: secondjob
    steps:
    - bash: echo build second job


- stage: QABuld
  jobs:
  - job: FirstJob
    steps:
    - bash: echo buld frst job
  - job: secondjob
    steps:
    - bash: echo build second job


- stage: ProdBuld
  jobs:
  - job: FirstJob
    steps:
    - bash: echo buld frst job
  - job: secondjob
    steps:
    - bash: echo build second job
